# Generated by Django 5.2.3 on 2025-06-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('week', models.DateField()),
                ('patient_footfall', models.IntegerField()),
                ('last_week_usage', models.IntegerField()),
                ('public_holiday', models.BooleanField()),
                ('rain_impact', models.BooleanField()),
                ('quantity_used', models.IntegerField()),
            ],
        ),
    ]
